version: 2.1

jobs:
  build:
    docker:
      - image: tuxonomics/numerics-utils:0.4

    steps:
      - checkout
      - run: make tests-ad-asan
      - run: make tests-rng-asan
      - run: make tests-mt-asan

workflows:
  "Run Tests":
    jobs:
      - build
