version: 2.1

jobs:
  build:
    docker:
      - image: tuxonomics/numerics-utils:0.3

    steps:
      - checkout
      - run: make tests-fwd-asan
      - run: make tests-rev-asan

workflows:
  "Run Tests":
    jobs:
      - build
